// ── Grounded LLM Generator ──────────────────────
import type { Citation, QueryResponse } from '@chorus/shared-types';

export async function generate(
  question: string,
  citations: Citation[],
): Promise<Omit<QueryResponse, 'processingTimeMs'>> {
  // Placeholder: call Gemini or OpenAI with grounding context
  const context = citations
    .map((c) => `File: ${c.filePath} (L${c.startLine}-L${c.endLine}):\n${c.snippet}`)
    .join('\n\n---\n\n');

  // In production: LLM call with structured prompt
  const answer = `Based on the codebase analysis, here is the answer to "${question}": [Answer would be generated by LLM using the retrieved context]`;

  return {
    answer,
    citations,
    confidence: 0.85,
  };
}
